// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MNKR_VariableCommand","status":true,"description":"イベントコマンドで変数が選べない組み合わせを使用可能にするプラグインコマンドを追加します。","parameters":{}},
{"name":"LL_ActorChoices","status":true,"description":"アクターを選択するプラグインコマンドを実装します。","parameters":{}}
];
