// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ChoiceActors","status":true,"description":"アクター選択肢作成プラグイン","parameters":{"AChoiceVariableNumber":"2","CancelChoiceMessage":"キャンセル"}},
{"name":"MNKR_VariableCommand","status":true,"description":"変数が使用できないイベントコマンドをプラグインコマンドで可能にします。","parameters":{}}
];
