// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MNKR_VariableCommand","status":true,"description":"変数が使用できないイベントコマンドをプラグインコマンドで可能にします。","parameters":{}},
{"name":"LL_ActorChoices","status":true,"description":"アクターを選択するプラグインコマンドを実装します。","parameters":{}}
];
